# Generated by Django 4.2 on 2023-04-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="news",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Tower News", max_length=50)),
                ("description", models.CharField(default="N/A", max_length=255)),
                ("newstype", models.CharField(default="information", max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="ris",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mtype", models.CharField(default="<event>", max_length=20)),
                ("title", models.CharField(default="News", max_length=50)),
                ("description", models.CharField(default="N/A", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="userData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.CharField(default="N/A", max_length=30)),
                ("fname", models.CharField(default="N/A", max_length=25)),
                ("lname", models.CharField(default="N/A", max_length=25)),
                ("department", models.CharField(default="N/A", max_length=20)),
                ("entry", models.CharField(default="N/A", max_length=10)),
                ("exit", models.CharField(default="N/A", max_length=10)),
                ("location", models.CharField(default="N/A", max_length=10)),
                ("visitors", models.CharField(default="0", max_length=5)),
                ("personalNo", models.CharField(default="N/A", max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="userTempData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.CharField(default="N/A", max_length=30)),
                ("fname", models.CharField(default="N/A", max_length=25)),
                ("lname", models.CharField(default="N/A", max_length=25)),
                ("department", models.CharField(default="N/A", max_length=20)),
                ("entry", models.CharField(default="N/A", max_length=10)),
                ("exit", models.CharField(default="N/A", max_length=10)),
                ("personalNo", models.CharField(default="N/A", max_length=10)),
            ],
        ),
    ]
